// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

let baseUrl = {
  contents: "https://api.bitbucket.org/2.0"
};

let username = {
  contents: ""
};

let appPassword = {
  contents: ""
};

function init() {
  username.contents = $$Deno.Env.getWithDefault("BITBUCKET_USERNAME", "");
  appPassword.contents = $$Deno.Env.getWithDefault("BITBUCKET_APP_PASSWORD", "");
}

function authHeaders() {
  let auth = btoa(username.contents + `:` + appPassword.contents);
  return Object.fromEntries([
    [
      "Authorization",
      `Basic ` + auth
    ],
    [
      "Content-Type",
      "application/json"
    ]
  ]);
}

async function fetchApi(path) {
  init();
  let headers = authHeaders();
  let result = await $$Deno.Fetch.get(baseUrl.contents + path, headers);
  if (result.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: JSON.stringify(result._0)
    };
  } else {
    return {
      TAG: "Error",
      _0: result._0
    };
  }
}

let tools = Object.fromEntries([
  [
    "bb_repo_list",
    {
      name: "bb_repo_list",
      description: "List Bitbucket repositories",
      inputSchema: {
      "type": "object",
      "properties": {
        "workspace": { "type": "string", "description": "Workspace slug" },
        "role": { "type": "string", "enum": ["owner", "admin", "contributor", "member"], "description": "Filter by role" }
      }
    }
    }
  ],
  [
    "bb_repo_view",
    {
      name: "bb_repo_view",
      description: "View repository details",
      inputSchema: {
      "type": "object",
      "properties": {
        "workspace": { "type": "string", "description": "Workspace slug" },
        "repo": { "type": "string", "description": "Repository slug" }
      },
      "required": ["workspace", "repo"]
    }
    }
  ],
  [
    "bb_issue_list",
    {
      name: "bb_issue_list",
      description: "List issues (requires issue tracker enabled)",
      inputSchema: {
      "type": "object",
      "properties": {
        "workspace": { "type": "string", "description": "Workspace slug" },
        "repo": { "type": "string", "description": "Repository slug" },
        "state": { "type": "string", "enum": ["new", "open", "resolved", "on hold", "invalid", "duplicate", "wontfix", "closed"], "description": "Issue state" }
      },
      "required": ["workspace", "repo"]
    }
    }
  ],
  [
    "bb_pr_list",
    {
      name: "bb_pr_list",
      description: "List pull requests",
      inputSchema: {
      "type": "object",
      "properties": {
        "workspace": { "type": "string", "description": "Workspace slug" },
        "repo": { "type": "string", "description": "Repository slug" },
        "state": { "type": "string", "enum": ["OPEN", "MERGED", "DECLINED", "SUPERSEDED"], "description": "PR state" }
      },
      "required": ["workspace", "repo"]
    }
    }
  ],
  [
    "bb_pr_view",
    {
      name: "bb_pr_view",
      description: "View a pull request",
      inputSchema: {
      "type": "object",
      "properties": {
        "workspace": { "type": "string", "description": "Workspace slug" },
        "repo": { "type": "string", "description": "Repository slug" },
        "id": { "type": "integer", "description": "Pull request ID" }
      },
      "required": ["workspace", "repo", "id"]
    }
    }
  ],
  [
    "bb_pipeline_list",
    {
      name: "bb_pipeline_list",
      description: "List pipelines",
      inputSchema: {
      "type": "object",
      "properties": {
        "workspace": { "type": "string", "description": "Workspace slug" },
        "repo": { "type": "string", "description": "Repository slug" }
      },
      "required": ["workspace", "repo"]
    }
    }
  ],
  [
    "bb_branches",
    {
      name: "bb_branches",
      description: "List branches",
      inputSchema: {
      "type": "object",
      "properties": {
        "workspace": { "type": "string", "description": "Workspace slug" },
        "repo": { "type": "string", "description": "Repository slug" }
      },
      "required": ["workspace", "repo"]
    }
    }
  ],
  [
    "bb_commits",
    {
      name: "bb_commits",
      description: "List recent commits",
      inputSchema: {
      "type": "object",
      "properties": {
        "workspace": { "type": "string", "description": "Workspace slug" },
        "repo": { "type": "string", "description": "Repository slug" },
        "branch": { "type": "string", "description": "Branch name (optional)" }
      },
      "required": ["workspace", "repo"]
    }
    }
  ],
  [
    "bb_workspaces",
    {
      name: "bb_workspaces",
      description: "List workspaces for authenticated user",
      inputSchema: {
      "type": "object",
      "properties": {}
    }
    }
  ],
  [
    "bb_user",
    {
      name: "bb_user",
      description: "Get current user info",
      inputSchema: {
      "type": "object",
      "properties": {}
    }
    }
  ]
]);

async function handleToolCall(name, args) {
  let argsDict = Stdlib_Option.getOr(Stdlib_JSON.Decode.object(args), {});
  let getString = key => Stdlib_Option.getOr(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.string), "");
  let getInt = key => Stdlib_Option.map(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.float), v => v | 0);
  let workspace = getString("workspace");
  let repo = getString("repo");
  switch (name) {
    case "bb_branches" :
      return await fetchApi(`/repositories/` + workspace + `/` + repo + `/refs/branches`);
    case "bb_commits" :
      let branch = getString("branch");
      let path = `/repositories/` + workspace + `/` + repo + `/commits`;
      let path$1 = branch !== "" ? path + `/` + branch : path;
      return await fetchApi(path$1);
    case "bb_issue_list" :
      let state = getString("state");
      let path$2 = `/repositories/` + workspace + `/` + repo + `/issues`;
      let path$3 = state !== "" ? path$2 + `?q=state="` + state + `"` : path$2;
      return await fetchApi(path$3);
    case "bb_pipeline_list" :
      return await fetchApi(`/repositories/` + workspace + `/` + repo + `/pipelines/`);
    case "bb_pr_list" :
      let state$1 = getString("state");
      let path$4 = `/repositories/` + workspace + `/` + repo + `/pullrequests`;
      let path$5 = state$1 !== "" ? path$4 + `?state=` + state$1 : path$4;
      return await fetchApi(path$5);
    case "bb_pr_view" :
      let id = Stdlib_Option.getOr(getInt("id"), 0);
      return await fetchApi(`/repositories/` + workspace + `/` + repo + `/pullrequests/` + id.toString());
    case "bb_repo_list" :
      let role = getString("role");
      let path$6 = workspace !== "" ? `/repositories/` + workspace : `/repositories`;
      let path$7 = role !== "" ? path$6 + `?role=` + role : path$6;
      return await fetchApi(path$7);
    case "bb_repo_view" :
      return await fetchApi(`/repositories/` + workspace + `/` + repo);
    case "bb_user" :
      return await fetchApi("/user");
    case "bb_workspaces" :
      return await fetchApi("/workspaces");
    default:
      return {
        TAG: "Error",
        _0: "Unknown tool: " + name
      };
  }
}

export {
  baseUrl,
  username,
  appPassword,
  init,
  authHeaders,
  fetchApi,
  tools,
  handleToolCall,
}
/* tools Not a pure module */
