// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

async function runTea(args) {
  let cmd = $$Deno.Command.$$new("tea", args.concat([
    "--output",
    "simple"
  ]), undefined);
  let output = await cmd.output();
  if (output.success) {
    return {
      TAG: "Ok",
      _0: $$Deno.Command.stdoutText(output)
    };
  } else {
    return {
      TAG: "Error",
      _0: $$Deno.Command.stderrText(output)
    };
  }
}

let tools = Object.fromEntries([
  [
    "tea_repo_list",
    {
      name: "tea_repo_list",
      description: "List Gitea repositories",
      inputSchema: {
      "type": "object",
      "properties": {
        "owner": { "type": "string", "description": "Owner (user or org)" },
        "starred": { "type": "boolean", "description": "List starred repos" },
        "limit": { "type": "integer", "description": "Max repos to list" }
      }
    }
    }
  ],
  [
    "tea_repo_view",
    {
      name: "tea_repo_view",
      description: "View repository details",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Repository (owner/repo)" }
      },
      "required": ["repo"]
    }
    }
  ],
  [
    "tea_issue_list",
    {
      name: "tea_issue_list",
      description: "List issues",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Repository (owner/repo)" },
        "state": { "type": "string", "enum": ["open", "closed", "all"], "description": "Issue state" },
        "kind": { "type": "string", "enum": ["issue", "pull"], "description": "Issue kind" }
      }
    }
    }
  ],
  [
    "tea_issue_view",
    {
      name: "tea_issue_view",
      description: "View an issue",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Repository" },
        "number": { "type": "integer", "description": "Issue number" }
      },
      "required": ["number"]
    }
    }
  ],
  [
    "tea_issue_create",
    {
      name: "tea_issue_create",
      description: "Create an issue",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Repository" },
        "title": { "type": "string", "description": "Issue title" },
        "description": { "type": "string", "description": "Issue body" }
      },
      "required": ["title"]
    }
    }
  ],
  [
    "tea_pr_list",
    {
      name: "tea_pr_list",
      description: "List pull requests",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Repository" },
        "state": { "type": "string", "enum": ["open", "closed", "all"], "description": "PR state" }
      }
    }
    }
  ],
  [
    "tea_pr_view",
    {
      name: "tea_pr_view",
      description: "View a pull request",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Repository" },
        "number": { "type": "integer", "description": "PR number" }
      },
      "required": ["number"]
    }
    }
  ],
  [
    "tea_pr_create",
    {
      name: "tea_pr_create",
      description: "Create a pull request",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Repository" },
        "title": { "type": "string", "description": "PR title" },
        "description": { "type": "string", "description": "PR description" },
        "head": { "type": "string", "description": "Head branch" },
        "base": { "type": "string", "description": "Base branch" }
      },
      "required": ["title", "head", "base"]
    }
    }
  ],
  [
    "tea_release_list",
    {
      name: "tea_release_list",
      description: "List releases",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Repository" }
      }
    }
    }
  ],
  [
    "tea_org_list",
    {
      name: "tea_org_list",
      description: "List organizations",
      inputSchema: {
      "type": "object",
      "properties": {}
    }
    }
  ],
  [
    "tea_login_list",
    {
      name: "tea_login_list",
      description: "List configured Gitea logins",
      inputSchema: {
      "type": "object",
      "properties": {}
    }
    }
  ]
]);

async function handleToolCall(name, args) {
  let argsDict = Stdlib_Option.getOr(Stdlib_JSON.Decode.object(args), {});
  let getString = key => Stdlib_Option.getOr(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.string), "");
  let getBool = key => Stdlib_Option.getOr(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.bool), false);
  let getInt = key => Stdlib_Option.map(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.float), v => v | 0);
  let repo = getString("repo");
  let repoArg = repo !== "" ? [
      "-r",
      repo
    ] : [];
  switch (name) {
    case "tea_issue_create" :
      let title = getString("title");
      let description = getString("description");
      let args$1 = [
        "issues",
        "create",
        "-t",
        title
      ];
      let args$2 = args$1.concat(repoArg);
      let args$3 = description !== "" ? args$2.concat([
          "-d",
          description
        ]) : args$2;
      return await runTea(args$3);
    case "tea_issue_list" :
      let state = getString("state");
      let kind = getString("kind");
      let args$4 = [
        "issues",
        "ls"
      ];
      let args$5 = args$4.concat(repoArg);
      let args$6 = state !== "" ? args$5.concat([
          "-s",
          state
        ]) : args$5;
      let args$7 = kind !== "" ? args$6.concat([
          "-k",
          kind
        ]) : args$6;
      return await runTea(args$7);
    case "tea_issue_view" :
      let number = Stdlib_Option.getOr(getInt("number"), 0);
      return await runTea([
        "issues",
        "view",
        number.toString()
      ].concat(repoArg));
    case "tea_login_list" :
      return await runTea([
        "logins",
        "ls"
      ]);
    case "tea_org_list" :
      return await runTea([
        "orgs",
        "ls"
      ]);
    case "tea_pr_create" :
      let title$1 = getString("title");
      let description$1 = getString("description");
      let head = getString("head");
      let base = getString("base");
      let args$8 = [
        "pulls",
        "create",
        "-t",
        title$1,
        "-H",
        head,
        "-B",
        base
      ];
      let args$9 = args$8.concat(repoArg);
      let args$10 = description$1 !== "" ? args$9.concat([
          "-d",
          description$1
        ]) : args$9;
      return await runTea(args$10);
    case "tea_pr_list" :
      let state$1 = getString("state");
      let args$11 = [
        "pulls",
        "ls"
      ];
      let args$12 = args$11.concat(repoArg);
      let args$13 = state$1 !== "" ? args$12.concat([
          "-s",
          state$1
        ]) : args$12;
      return await runTea(args$13);
    case "tea_pr_view" :
      let number$1 = Stdlib_Option.getOr(getInt("number"), 0);
      return await runTea([
        "pulls",
        "view",
        number$1.toString()
      ].concat(repoArg));
    case "tea_release_list" :
      return await runTea([
        "releases",
        "ls"
      ].concat(repoArg));
    case "tea_repo_list" :
      let owner = getString("owner");
      let starred = getBool("starred");
      let limit = getInt("limit");
      let args$14 = [
        "repos",
        "ls"
      ];
      let args$15 = owner !== "" ? args$14.concat([
          "-o",
          owner
        ]) : args$14;
      let args$16 = starred ? args$15.concat(["--starred"]) : args$15;
      let args$17 = limit !== undefined ? args$16.concat([
          "-l",
          limit.toString()
        ]) : args$16;
      return await runTea(args$17);
    case "tea_repo_view" :
      return await runTea([
        "repos",
        "view"
      ].concat(repoArg));
    default:
      return {
        TAG: "Error",
        _0: "Unknown tool: " + name
      };
  }
}

export {
  runTea,
  tools,
  handleToolCall,
}
/* tools Not a pure module */
