// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

async function runGh(args) {
  let cmd = $$Deno.Command.$$new("gh", args, undefined);
  let output = await cmd.output();
  if (output.success) {
    return {
      TAG: "Ok",
      _0: $$Deno.Command.stdoutText(output)
    };
  } else {
    return {
      TAG: "Error",
      _0: $$Deno.Command.stderrText(output)
    };
  }
}

let tools = Object.fromEntries([
  [
    "gh_repo_list",
    {
      name: "gh_repo_list",
      description: "List GitHub repositories",
      inputSchema: {
      "type": "object",
      "properties": {
        "owner": { "type": "string", "description": "Owner (user or org)" },
        "limit": { "type": "integer", "description": "Max repos to list" },
        "visibility": { "type": "string", "enum": ["public", "private", "internal"], "description": "Filter by visibility" }
      }
    }
    }
  ],
  [
    "gh_repo_view",
    {
      name: "gh_repo_view",
      description: "View repository details",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Repository (owner/repo)" }
      },
      "required": ["repo"]
    }
    }
  ],
  [
    "gh_repo_clone",
    {
      name: "gh_repo_clone",
      description: "Clone a repository",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Repository (owner/repo or URL)" },
        "directory": { "type": "string", "description": "Target directory" }
      },
      "required": ["repo"]
    }
    }
  ],
  [
    "gh_issue_list",
    {
      name: "gh_issue_list",
      description: "List issues in a repository",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Repository (owner/repo)" },
        "state": { "type": "string", "enum": ["open", "closed", "all"], "description": "Issue state" },
        "label": { "type": "string", "description": "Filter by label" },
        "assignee": { "type": "string", "description": "Filter by assignee" },
        "limit": { "type": "integer", "description": "Max issues to list" }
      }
    }
    }
  ],
  [
    "gh_issue_view",
    {
      name: "gh_issue_view",
      description: "View an issue",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Repository (owner/repo)" },
        "number": { "type": "integer", "description": "Issue number" }
      },
      "required": ["number"]
    }
    }
  ],
  [
    "gh_issue_create",
    {
      name: "gh_issue_create",
      description: "Create a new issue",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Repository (owner/repo)" },
        "title": { "type": "string", "description": "Issue title" },
        "body": { "type": "string", "description": "Issue body" },
        "labels": { "type": "array", "items": { "type": "string" }, "description": "Labels to add" },
        "assignees": { "type": "array", "items": { "type": "string" }, "description": "Assignees" }
      },
      "required": ["title"]
    }
    }
  ],
  [
    "gh_pr_list",
    {
      name: "gh_pr_list",
      description: "List pull requests",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Repository (owner/repo)" },
        "state": { "type": "string", "enum": ["open", "closed", "merged", "all"], "description": "PR state" },
        "base": { "type": "string", "description": "Base branch" },
        "head": { "type": "string", "description": "Head branch" },
        "limit": { "type": "integer", "description": "Max PRs to list" }
      }
    }
    }
  ],
  [
    "gh_pr_view",
    {
      name: "gh_pr_view",
      description: "View a pull request",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Repository (owner/repo)" },
        "number": { "type": "integer", "description": "PR number" }
      },
      "required": ["number"]
    }
    }
  ],
  [
    "gh_pr_create",
    {
      name: "gh_pr_create",
      description: "Create a pull request",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Repository (owner/repo)" },
        "title": { "type": "string", "description": "PR title" },
        "body": { "type": "string", "description": "PR body" },
        "base": { "type": "string", "description": "Base branch" },
        "head": { "type": "string", "description": "Head branch" },
        "draft": { "type": "boolean", "description": "Create as draft" }
      },
      "required": ["title"]
    }
    }
  ],
  [
    "gh_pr_merge",
    {
      name: "gh_pr_merge",
      description: "Merge a pull request",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Repository (owner/repo)" },
        "number": { "type": "integer", "description": "PR number" },
        "method": { "type": "string", "enum": ["merge", "squash", "rebase"], "description": "Merge method" },
        "delete": { "type": "boolean", "description": "Delete branch after merge" }
      },
      "required": ["number"]
    }
    }
  ],
  [
    "gh_release_list",
    {
      name: "gh_release_list",
      description: "List releases",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Repository (owner/repo)" },
        "limit": { "type": "integer", "description": "Max releases to list" }
      }
    }
    }
  ],
  [
    "gh_workflow_list",
    {
      name: "gh_workflow_list",
      description: "List workflow runs",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Repository (owner/repo)" },
        "workflow": { "type": "string", "description": "Workflow name or ID" },
        "limit": { "type": "integer", "description": "Max runs to list" }
      }
    }
    }
  ],
  [
    "gh_auth_status",
    {
      name: "gh_auth_status",
      description: "Check authentication status",
      inputSchema: {
      "type": "object",
      "properties": {}
    }
    }
  ]
]);

async function handleToolCall(name, args) {
  let argsDict = Stdlib_Option.getOr(Stdlib_JSON.Decode.object(args), {});
  let getString = key => Stdlib_Option.getOr(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.string), "");
  let getBool = key => Stdlib_Option.getOr(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.bool), false);
  let getInt = key => Stdlib_Option.map(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.float), v => v | 0);
  let getArray = key => Stdlib_Option.getOr(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.array), []);
  let repo = getString("repo");
  let repoArg = repo !== "" ? [
      "-R",
      repo
    ] : [];
  switch (name) {
    case "gh_auth_status" :
      return await runGh([
        "auth",
        "status"
      ]);
    case "gh_issue_create" :
      let title = getString("title");
      let body = getString("body");
      let labels = Stdlib_Array.filterMap(getArray("labels"), Stdlib_JSON.Decode.string);
      let assignees = Stdlib_Array.filterMap(getArray("assignees"), Stdlib_JSON.Decode.string);
      let args$1 = [
        "issue",
        "create",
        "-t",
        title
      ];
      let args$2 = args$1.concat(repoArg);
      let args$3 = body !== "" ? args$2.concat([
          "-b",
          body
        ]) : args$2;
      let args$4 = labels.length !== 0 ? args$3.concat([
          "-l",
          labels.join(",")
        ]) : args$3;
      let args$5 = assignees.length !== 0 ? args$4.concat([
          "-a",
          assignees.join(",")
        ]) : args$4;
      return await runGh(args$5);
    case "gh_issue_list" :
      let state = getString("state");
      let label = getString("label");
      let assignee = getString("assignee");
      let limit = getInt("limit");
      let args$6 = [
        "issue",
        "list"
      ];
      let args$7 = args$6.concat(repoArg);
      let args$8 = state !== "" ? args$7.concat([
          "-s",
          state
        ]) : args$7;
      let args$9 = label !== "" ? args$8.concat([
          "-l",
          label
        ]) : args$8;
      let args$10 = assignee !== "" ? args$9.concat([
          "-a",
          assignee
        ]) : args$9;
      let args$11 = limit !== undefined ? args$10.concat([
          "-L",
          limit.toString()
        ]) : args$10;
      return await runGh(args$11.concat([
        "--json",
        "number,title,state,author,labels"
      ]));
    case "gh_issue_view" :
      let number = Stdlib_Option.getOr(getInt("number"), 0);
      return await runGh([
        "issue",
        "view",
        number.toString()
      ].concat(repoArg.concat([
        "--json",
        "number,title,body,state,author,labels,comments"
      ])));
    case "gh_pr_create" :
      let title$1 = getString("title");
      let body$1 = getString("body");
      let base = getString("base");
      let head = getString("head");
      let draft = getBool("draft");
      let args$12 = [
        "pr",
        "create",
        "-t",
        title$1
      ];
      let args$13 = args$12.concat(repoArg);
      let args$14 = body$1 !== "" ? args$13.concat([
          "-b",
          body$1
        ]) : args$13;
      let args$15 = base !== "" ? args$14.concat([
          "-B",
          base
        ]) : args$14;
      let args$16 = head !== "" ? args$15.concat([
          "-H",
          head
        ]) : args$15;
      let args$17 = draft ? args$16.concat(["--draft"]) : args$16;
      return await runGh(args$17);
    case "gh_pr_list" :
      let state$1 = getString("state");
      let base$1 = getString("base");
      let head$1 = getString("head");
      let limit$1 = getInt("limit");
      let args$18 = [
        "pr",
        "list"
      ];
      let args$19 = args$18.concat(repoArg);
      let args$20 = state$1 !== "" ? args$19.concat([
          "-s",
          state$1
        ]) : args$19;
      let args$21 = base$1 !== "" ? args$20.concat([
          "-B",
          base$1
        ]) : args$20;
      let args$22 = head$1 !== "" ? args$21.concat([
          "-H",
          head$1
        ]) : args$21;
      let args$23 = limit$1 !== undefined ? args$22.concat([
          "-L",
          limit$1.toString()
        ]) : args$22;
      return await runGh(args$23.concat([
        "--json",
        "number,title,state,author,baseRefName,headRefName"
      ]));
    case "gh_pr_merge" :
      let number$1 = Stdlib_Option.getOr(getInt("number"), 0);
      let mergeMethod = getString("method");
      let deleteBranch = getBool("delete");
      let args$24 = [
        "pr",
        "merge",
        number$1.toString()
      ];
      let args$25 = args$24.concat(repoArg);
      let args$26;
      switch (mergeMethod) {
        case "rebase" :
          args$26 = args$25.concat(["--rebase"]);
          break;
        case "squash" :
          args$26 = args$25.concat(["--squash"]);
          break;
        default:
          args$26 = args$25.concat(["--merge"]);
      }
      let args$27 = deleteBranch ? args$26.concat(["--delete-branch"]) : args$26;
      return await runGh(args$27);
    case "gh_pr_view" :
      let number$2 = Stdlib_Option.getOr(getInt("number"), 0);
      return await runGh([
        "pr",
        "view",
        number$2.toString()
      ].concat(repoArg.concat([
        "--json",
        "number,title,body,state,author,baseRefName,headRefName,reviews"
      ])));
    case "gh_release_list" :
      let limit$2 = getInt("limit");
      let args$28 = [
        "release",
        "list"
      ];
      let args$29 = args$28.concat(repoArg);
      let args$30 = limit$2 !== undefined ? args$29.concat([
          "-L",
          limit$2.toString()
        ]) : args$29;
      return await runGh(args$30);
    case "gh_repo_clone" :
      let directory = getString("directory");
      let args$31 = [
        "repo",
        "clone",
        repo
      ];
      let args$32 = directory !== "" ? args$31.concat([directory]) : args$31;
      return await runGh(args$32);
    case "gh_repo_list" :
      let owner = getString("owner");
      let limit$3 = getInt("limit");
      let visibility = getString("visibility");
      let args$33 = [
        "repo",
        "list"
      ];
      let args$34 = owner !== "" ? args$33.concat([owner]) : args$33;
      let args$35 = limit$3 !== undefined ? args$34.concat([
          "-L",
          limit$3.toString()
        ]) : args$34;
      let args$36 = visibility !== "" ? args$35.concat([
          "--visibility",
          visibility
        ]) : args$35;
      return await runGh(args$36.concat([
        "--json",
        "name,description,url,visibility"
      ]));
    case "gh_repo_view" :
      return await runGh([
        "repo",
        "view"
      ].concat(repoArg.concat([
        "--json",
        "name,description,url,stargazerCount,forkCount"
      ])));
    case "gh_workflow_list" :
      let workflow = getString("workflow");
      let limit$4 = getInt("limit");
      let args$37 = [
        "run",
        "list"
      ];
      let args$38 = args$37.concat(repoArg);
      let args$39 = workflow !== "" ? args$38.concat([
          "-w",
          workflow
        ]) : args$38;
      let args$40 = limit$4 !== undefined ? args$39.concat([
          "-L",
          limit$4.toString()
        ]) : args$39;
      return await runGh(args$40.concat([
        "--json",
        "databaseId,displayTitle,status,conclusion,createdAt"
      ]));
    default:
      return {
        TAG: "Error",
        _0: "Unknown tool: " + name
      };
  }
}

export {
  runGh,
  tools,
  handleToolCall,
}
/* tools Not a pure module */
