// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

async function runGlab(args) {
  let cmd = $$Deno.Command.$$new("glab", args, undefined);
  let output = await cmd.output();
  if (output.success) {
    return {
      TAG: "Ok",
      _0: $$Deno.Command.stdoutText(output)
    };
  } else {
    return {
      TAG: "Error",
      _0: $$Deno.Command.stderrText(output)
    };
  }
}

let tools = Object.fromEntries([
  [
    "glab_project_list",
    {
      name: "glab_project_list",
      description: "List GitLab projects",
      inputSchema: {
      "type": "object",
      "properties": {
        "group": { "type": "string", "description": "Filter by group/namespace" },
        "mine": { "type": "boolean", "description": "List only my projects" },
        "starred": { "type": "boolean", "description": "List starred projects" }
      }
    }
    }
  ],
  [
    "glab_project_view",
    {
      name: "glab_project_view",
      description: "View project details",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Project path (group/project)" }
      },
      "required": ["repo"]
    }
    }
  ],
  [
    "glab_issue_list",
    {
      name: "glab_issue_list",
      description: "List issues",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Project path" },
        "state": { "type": "string", "enum": ["opened", "closed", "all"], "description": "Issue state" },
        "label": { "type": "string", "description": "Filter by label" },
        "assignee": { "type": "string", "description": "Filter by assignee" }
      }
    }
    }
  ],
  [
    "glab_issue_view",
    {
      name: "glab_issue_view",
      description: "View an issue",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Project path" },
        "number": { "type": "integer", "description": "Issue IID" }
      },
      "required": ["number"]
    }
    }
  ],
  [
    "glab_issue_create",
    {
      name: "glab_issue_create",
      description: "Create an issue",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Project path" },
        "title": { "type": "string", "description": "Issue title" },
        "description": { "type": "string", "description": "Issue description" },
        "labels": { "type": "array", "items": { "type": "string" }, "description": "Labels" },
        "assignees": { "type": "array", "items": { "type": "string" }, "description": "Assignees" }
      },
      "required": ["title"]
    }
    }
  ],
  [
    "glab_mr_list",
    {
      name: "glab_mr_list",
      description: "List merge requests",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Project path" },
        "state": { "type": "string", "enum": ["opened", "closed", "merged", "all"], "description": "MR state" },
        "draft": { "type": "boolean", "description": "Filter by draft status" }
      }
    }
    }
  ],
  [
    "glab_mr_view",
    {
      name: "glab_mr_view",
      description: "View a merge request",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Project path" },
        "number": { "type": "integer", "description": "MR IID" }
      },
      "required": ["number"]
    }
    }
  ],
  [
    "glab_mr_create",
    {
      name: "glab_mr_create",
      description: "Create a merge request",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Project path" },
        "title": { "type": "string", "description": "MR title" },
        "description": { "type": "string", "description": "MR description" },
        "source": { "type": "string", "description": "Source branch" },
        "target": { "type": "string", "description": "Target branch" },
        "draft": { "type": "boolean", "description": "Create as draft" }
      },
      "required": ["title"]
    }
    }
  ],
  [
    "glab_mr_merge",
    {
      name: "glab_mr_merge",
      description: "Merge a merge request",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Project path" },
        "number": { "type": "integer", "description": "MR IID" },
        "squash": { "type": "boolean", "description": "Squash commits" },
        "removeSource": { "type": "boolean", "description": "Remove source branch" }
      },
      "required": ["number"]
    }
    }
  ],
  [
    "glab_pipeline_list",
    {
      name: "glab_pipeline_list",
      description: "List pipelines",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Project path" },
        "status": { "type": "string", "enum": ["running", "pending", "success", "failed", "canceled"], "description": "Filter by status" }
      }
    }
    }
  ],
  [
    "glab_ci_status",
    {
      name: "glab_ci_status",
      description: "Show CI/CD status for current branch",
      inputSchema: {
      "type": "object",
      "properties": {
        "repo": { "type": "string", "description": "Project path" },
        "branch": { "type": "string", "description": "Branch name" }
      }
    }
    }
  ],
  [
    "glab_auth_status",
    {
      name: "glab_auth_status",
      description: "Check authentication status",
      inputSchema: {
      "type": "object",
      "properties": {}
    }
    }
  ]
]);

async function handleToolCall(name, args) {
  let argsDict = Stdlib_Option.getOr(Stdlib_JSON.Decode.object(args), {});
  let getString = key => Stdlib_Option.getOr(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.string), "");
  let getBool = key => Stdlib_Option.getOr(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.bool), false);
  let getInt = key => Stdlib_Option.map(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.float), v => v | 0);
  let getArray = key => Stdlib_Option.getOr(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.array), []);
  let repo = getString("repo");
  let repoArg = repo !== "" ? [
      "-R",
      repo
    ] : [];
  switch (name) {
    case "glab_auth_status" :
      return await runGlab([
        "auth",
        "status"
      ]);
    case "glab_ci_status" :
      let branch = getString("branch");
      let args$1 = [
        "ci",
        "status"
      ];
      let args$2 = args$1.concat(repoArg);
      let args$3 = branch !== "" ? args$2.concat([
          "-b",
          branch
        ]) : args$2;
      return await runGlab(args$3);
    case "glab_issue_create" :
      let title = getString("title");
      let description = getString("description");
      let labels = Stdlib_Array.filterMap(getArray("labels"), Stdlib_JSON.Decode.string);
      let assignees = Stdlib_Array.filterMap(getArray("assignees"), Stdlib_JSON.Decode.string);
      let args$4 = [
        "issue",
        "create",
        "-t",
        title
      ];
      let args$5 = args$4.concat(repoArg);
      let args$6 = description !== "" ? args$5.concat([
          "-d",
          description
        ]) : args$5;
      let args$7 = labels.length !== 0 ? args$6.concat([
          "-l",
          labels.join(",")
        ]) : args$6;
      let args$8 = assignees.length !== 0 ? args$7.concat([
          "-a",
          assignees.join(",")
        ]) : args$7;
      return await runGlab(args$8);
    case "glab_issue_list" :
      let state = getString("state");
      let label = getString("label");
      let assignee = getString("assignee");
      let args$9 = [
        "issue",
        "list"
      ];
      let args$10 = args$9.concat(repoArg);
      let args$11 = state !== "" ? args$10.concat([
          "-s",
          state
        ]) : args$10;
      let args$12 = label !== "" ? args$11.concat([
          "-l",
          label
        ]) : args$11;
      let args$13 = assignee !== "" ? args$12.concat([
          "-a",
          assignee
        ]) : args$12;
      return await runGlab(args$13);
    case "glab_issue_view" :
      let number = Stdlib_Option.getOr(getInt("number"), 0);
      return await runGlab([
        "issue",
        "view",
        number.toString()
      ].concat(repoArg));
    case "glab_mr_create" :
      let title$1 = getString("title");
      let description$1 = getString("description");
      let source = getString("source");
      let target = getString("target");
      let draft = getBool("draft");
      let args$14 = [
        "mr",
        "create",
        "-t",
        title$1
      ];
      let args$15 = args$14.concat(repoArg);
      let args$16 = description$1 !== "" ? args$15.concat([
          "-d",
          description$1
        ]) : args$15;
      let args$17 = source !== "" ? args$16.concat([
          "-s",
          source
        ]) : args$16;
      let args$18 = target !== "" ? args$17.concat([
          "-b",
          target
        ]) : args$17;
      let args$19 = draft ? args$18.concat(["--draft"]) : args$18;
      return await runGlab(args$19);
    case "glab_mr_list" :
      let state$1 = getString("state");
      let draft$1 = getBool("draft");
      let args$20 = [
        "mr",
        "list"
      ];
      let args$21 = args$20.concat(repoArg);
      let args$22 = state$1 !== "" ? args$21.concat([
          "-s",
          state$1
        ]) : args$21;
      let args$23 = draft$1 ? args$22.concat(["--draft"]) : args$22;
      return await runGlab(args$23);
    case "glab_mr_merge" :
      let number$1 = Stdlib_Option.getOr(getInt("number"), 0);
      let squash = getBool("squash");
      let removeSource = getBool("removeSource");
      let args$24 = [
        "mr",
        "merge",
        number$1.toString()
      ];
      let args$25 = args$24.concat(repoArg);
      let args$26 = squash ? args$25.concat(["--squash"]) : args$25;
      let args$27 = removeSource ? args$26.concat(["--remove-source-branch"]) : args$26;
      return await runGlab(args$27);
    case "glab_mr_view" :
      let number$2 = Stdlib_Option.getOr(getInt("number"), 0);
      return await runGlab([
        "mr",
        "view",
        number$2.toString()
      ].concat(repoArg));
    case "glab_pipeline_list" :
      let status = getString("status");
      let args$28 = [
        "pipeline",
        "list"
      ];
      let args$29 = args$28.concat(repoArg);
      let args$30 = status !== "" ? args$29.concat([
          "-s",
          status
        ]) : args$29;
      return await runGlab(args$30);
    case "glab_project_list" :
      let group = getString("group");
      let mine = getBool("mine");
      let starred = getBool("starred");
      let args$31 = [
        "repo",
        "list"
      ];
      let args$32 = group !== "" ? args$31.concat([
          "-g",
          group
        ]) : args$31;
      let args$33 = mine ? args$32.concat(["--mine"]) : args$32;
      let args$34 = starred ? args$33.concat(["--starred"]) : args$33;
      return await runGlab(args$34);
    case "glab_project_view" :
      return await runGlab([
        "repo",
        "view"
      ].concat(repoArg));
    default:
      return {
        TAG: "Error",
        _0: "Unknown tool: " + name
      };
  }
}

export {
  runGlab,
  tools,
  handleToolCall,
}
/* tools Not a pure module */
